name: This Beautiful World
description: A series of adventures and vignettes
url: http://una.github.io/travels
markdown: redcarpet
highlighter: pygments # or rouge or null
permalink: pretty
exclude: ["node_modules", "gulpfile.js", "package.json", "source_files", "Gemfile", "Gemfile.lock", "LICENSE"]
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
twitter_username: una
github_username:  una